# Generated by Django 3.0.5 on 2022-04-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LA_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LA_question_num', models.IntegerField(unique=True)),
                ('LA_question_Text', models.CharField(max_length=200)),
                ('LA_question_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Level')),
            ],
        ),
        migrations.CreateModel(
            name='LA_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LA_choice_num', models.IntegerField(unique=True)),
                ('LA_choice_text', models.CharField(max_length=200)),
                ('LA_choice_isCorrect', models.BooleanField(default=False)),
                ('LA_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.LA_Question')),
            ],
        ),
    ]
