# Generated by Django 3.0.5 on 2022-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='levelName',
            field=models.CharField(max_length=15),
        ),
    ]
