# Generated by Django 3.0.5 on 2022-04-17 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Quiz', '0002_auto_20220416_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='la_question',
            old_name='LA_question_Text',
            new_name='LA_question_text',
        ),
    ]
