# Generated by Django 3.0.5 on 2022-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Quiz', '0003_auto_20220417_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_of_questions', models.IntegerField()),
                ('score_to_pass', models.IntegerField(help_text='Required score in %')),
                ('level', models.CharField(
                    choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                    max_length=15)),
            ],
        ),
    ]
