# Generated by Django 3.0.5 on 2022-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Quiz', '0005_auto_20220417_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='question_level',
            field=models.CharField(
                choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                default='Beginner', max_length=15),
        ),
    ]
