# Generated by Django 3.0.5 on 2022-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Quiz', '0006_auto_20220417_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_num',
            field=models.IntegerField(),
        ),
    ]
