# Generated by Django 3.0.5 on 2022-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Quiz', '0007_auto_20220418_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(),
        ),
    ]
