# Generated by Django 3.0.5 on 2022-04-24 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0008_auto_20220419_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('user_level', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_num',
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(
                choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                default='Beginner', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='total',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_of_questions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_to_pass',
            field=models.IntegerField(default=67, help_text='Required score in %'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='mark',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question'),
        ),
    ]
