# Generated by Django 4.0.4 on 2022-06-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_alter_answer_id_alter_mark_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='This is a test quiz.'),
        ),
    ]
