# Generated by Django 4.0.4 on 2022-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='This is a test quiz.'),
        ),
    ]
