# Generated by Django 4.0.4 on 2022-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_alter_mark_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='user_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=25),
        ),
    ]
